### ISSUE TITLE
download processed datasets

### ISSUE THREAD

**Issue by givkashi** [BITszwang/DPT#1]
Hi, I want to download processed datasets and other files from this[ link](https://pan.baidu.com/s/1QMqg445nSkuudAI82EL1qQ#list/path=%2F) but I can't do that without signing up.
Could you please share these files with google drive or suggest any solution for download?

**Comment by BITszwang** [comment]
Thanks for your attention. I will provide a OneDrive link as soon as possible. @givkashi

**Comment by BITszwang** [comment]
Thanks for your patience. You can download all the files from [OneDrive](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/EvZJ4B_1_dxAo5KSwYBx3K0BdYqbnTTUbjt2mDjlp3JyDw?e=5Fz8x1) with the password **912V**. @givkashi

**Comment by givkashi** [comment]
> Thanks for your patience. You can download all the files from [OneDrive](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/EvZJ4B_1_dxAo5KSwYBx3K0BdYqbnTTUbjt2mDjlp3JyDw?e=5Fz8x1) with the password **912V**. @givkashi

Thanks.
